[fix/cannon-placement] cannon respawn method revision
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-07 pull request #52
Opened 2024-12-14 15:49 UTC by slwjackie

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] Feat : 새로운 기능 추가
- [ ] Bug : 버그 발견
- [x] Fix : 버그 수정
- [ ] Docs : 문서 수정
- [ ] Style : 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
- [ ] Refactor : 코드 리펙토링

### 변경 사항
- 대포 리스폰 과정에서의 충돌 방지
  - 대포의 isKinematic 조절
  - 대포의 position freeze

### 테스트 결과
- 대포가 리스폰 되어 땅에 착지하는 순간 position이 고정되는 것을 확인함

### 참고 사항
- Cannon object collider의 isTrigger를 체크해줘야 의도한대로 동작합니당
- 추후에 경사면에서도 자연스럽게 보이게 수정할 예정

### 리뷰 요청
- [ ] 대포가 리스폰하는 과정에서 충돌이 일어나지 않는지
- [ ] 대포가 ground와 충돌한 후에 position freeze되는지

2024-12-15 01:09 UTC, isaac0622 requested changes
라인 렌더러 관련 사항, 대포 땅바닥 착지 관련 사항 검토 부탁드립니당

2024-12-15 02:37 UTC, kunwoo-kim-9 commented
1. 시작 시 공이 안 보이는데 카메라 위치 수정 필요해 보입니다. (대포 소환하면 이동해서 잘 잡아줌)
2. sticky ball 이 땅에 좀 박히는 현상 -> 딱 붙는 느낌은 좋은데, 다음 대포 생성 시 문제 많이 일어남
3. 스테이지 3에서 포물선 안 보임 (이석이 말처럼)
4. 스테이지 3 첫 부분 경사 어떻게 올라갈지 모르겠네.. (sticky로 붙이고 그 다음 대포가 또 굴러내려 와서) -> 세기 조정 아직 안 된 건지 코멘트 부탁

2024-12-15 15:12 UTC, isaac0622 commented
라인렌더러 이슈는 잘 해결되었고, 대포의 형성 문제도 해결됨. 다만 언급해준 것처럼, 대포가 있는 모습은 다소 부자연스러울 때가 있음 (한 10에 한번정도?). 아래 사진 참고
![image](https://github.com/user-attachments/assets/6122e157-d548-465a-b290-90a9021e46b8)
기능적으로 문제는 없기에 approve 하고자 함.

근데 죽었을 때 엔딩이 제대로 안 뜨는 것 같음. 혹시 엔딩과 관련된 부분에 수정이 있었는지 궁금함. 또,

2024-12-15 15:13 UTC, isaac0622 commented
실수로 닫아버렸네요 reopen 하겠슴다

2024-12-16 11:00 UTC, minseo25 approved these changes

2024-12-16 11:01 UTC, kunwoo-kim-9 approved these changes
LGTM

2024-12-16 13:48 UTC, closed without merging