[Fix/minor-bugs] object scale, collider, position 조정
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-07 pull request #58
Opened 2024-12-20 12:33 UTC by slwjackie

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] Feat : 새로운 기능 추가
- [ ] Bug : 버그 발견
- [x] Fix : 버그 수정
- [ ] Docs : 문서 수정
- [ ] Style : 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
- [ ] Refactor : 코드 리펙토링

### 변경 사항
- stage1,3 scene 수정
  - stage1: collider 수정 및 tag 추가/ 나무 scale 변경
  - stage3: collider 수정/ 나무 position, scale 변경

- CannonControl 코드 일부 수정
  -  AreAnglesClose 메소드 추가

### 테스트 결과
- 공이 정지한 위치와 무관하게 버그없이 잘 동작함

### 참고사항
- stage1에서 나무의 scale을 조정하면서 stage조망 애니메이션 카메라가 나무 사이를 뚫고 지나가는데 혹시 수정하고 싶으면 말해주세용

### 리뷰 요청
- [ ] 버그 없이 잘 동작하는지 전반적인 검토 부탁합니당

2024-12-20 14:53 UTC, yeeseokoh requested changes
Stage1에서 Ball이 시작할 때부터 없음. 또한, 스페이스바를 눌러도 대포가 생성되지 않음.

2024-12-20 15:05 UTC, isaac0622 approved these changes
다시 확인해보니 정상적인 startscene에서부터 하니 작동됩니당. 스테이지 3 씬이 조금 작아져서 선풍기의 영향 범위가 다소 너무 커져서 조금 더 어려워진 듯 한데.... 뭐 막판이니까 어려워져도 되겠쥬

스테이지 1에서 카메라가 말한대로 가리기는 하는데 수정하면 좋지만 그것도 일이니까 그냥 approve 해도 좋을 듯합니다. 고생하셨어유

2024-12-20 19:06 UTC, kunwoo-kim-9 commented
![image](https://github.com/user-attachments/assets/b4f7d4ae-ad92-4172-9958-d921408e3b95)
스테이지 3 앞쪽 나무들 치울까요..?

나머지는 모두 확인했고 버그 없습니다!

2024-12-21 02:46 UTC, minseo25 approved these changes
![image](https://github.com/user-attachments/assets/554c7c11-6620-4952-bfaf-3d643d90d4ad)

 문제 없이 잘 동작합니다~~
 별개로 LINELENDERER 색도 이쁘군요

2024-12-21 02:47 UTC, merged